version: "3"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/db-data:/var/lib/postgresql/data

  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"

  backend:
    build:
      context: ./
    depends_on:
      - postgres
    environment:
      - NODE_ENV=${NODE_ENV}
      - jwtSecret=${jwtSecret}
      - jwtResetSecret=${jwtResetSecret}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - CLIENT_ADDRESS=${CLIENT_ADDRESS}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - 5000:5000
